title: Shijie's Blog
author: Shijie Xie
email: xxshijie@seas.upenn.edu
description: Hard work always pays off.
url: "https://cjxiee.github.io/blog/" 

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Hard work always pays off
  avatar_url: https://i.loli.net/2019/09/07/wiBh3uMWRUaLX5K.png 
  date_format: "%b %d"
  back_to: "Home"
  social_links:
    rss: RSS
    github:  cjxiee
    instagram: lylamxxsj
    linkedin: shijie-xie-126157205

